
---

### `03-Deploying-Your-First-Application/simple-app.yaml`

```yaml
# In this file, we define two Kubernetes objects: a Deployment and a Service.
# Note the '---' separator which allows defining multiple resources in one file.

# ------------------- Deployment ------------------- #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes-container
        image: "paulbouwer/hello-kubernetes:1.7"
        ports:
        - containerPort: 8080

---

# -------------------- Service -------------------- #

apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-service
spec:
  type: NodePort
  selector:
    app: hello-kubernetes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # NodePort is the external port on the node to access the service
      # If not specified, Kubernetes will assign a random port.
      nodePort: 30001
