apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: kube-demo-app
type: Opaque
data:
  # The values are base64 encoded.
  # 'postgres' in base64 is 'cG9zdGdyZXM='
  # A strong password like 'SuperSecret123!' in base64 is 'U3VwZXJTZWNyZXQxMjMh'
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: U3VwZXJTZWNyZXQxMjMh